{% set name = "chardet" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b3b6ff479a8c414bc3fa2c0852995695c4a026dcd6d0633b2dd092ca39c1cf7

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

# Win64 some encodings tests failed
# tests\\iso-8859-9-turkish\\wikitop_tr_ISO-8859-9.txt-iso-8859-9]
{% set skip_broken_tests = [
    "test_encoding_detection",
    "test_encoding_detection_rename_legacy"
] %}

test:
  source_files:
    - tests
    - test.py
  imports:
    - chardet
    - chardet.metadata
    - chardet.sbcharsetprober
    - chardet.cli.chardetect
    - chardet.universaldetector
    - chardet.version
  requires:
    - pip
    - pytest
    # - pytest-xdist
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - chardetect --help
    - pytest test.py -vv --color=yes  # [not win]
    - pytest test.py -vv --color=yes -k "not ({{ skip_broken_tests | join(' or ') }})"  # [win]

about:
  home: https://github.com/chardet/chardet
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    Chardet is a character encoding detector for Python. It supports a wide range of encodings,
    including ASCII, UTF variants, various East Asian encodings (EUC, ISO-2022, Shift_JIS),
    and many others. Chardet uses statistical models and heuristics to guess the most likely encoding.
  doc_url: https://chardet.readthedocs.io
  dev_url: https://github.com/chardet/chardet

extra:
  recipe-maintainers:
    - dan-blanchard
    - jschueller
    - sigmavirus24
    - nehaljwani
