{% set name = "chardet" %}
{% set version = "5.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b3b6ff479a8c414bc3fa2c0852995695c4a026dcd6d0633b2dd092ca39c1cf7

build:
  number: 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
    - test.py
  files:
    - recipe_conftest.py
  imports:
    - chardet
    - chardet.metadata
    - chardet.sbcharsetprober
    - chardet.cli.chardetect
    - chardet.universaldetector
    - chardet.version
  requires:
    - pip
    - pytest
    - pytest-xdist
    - py
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - chardetect --help
    - copy recipe_conftest.py conftest.py  # [win]
    - pytest -n auto -vv --color=yes test.py

about:
  home: https://github.com/chardet/chardet
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    Chardet is a character encoding detector for Python. It supports a wide range of encodings,
    including ASCII, UTF variants, various East Asian encodings (EUC, ISO-2022, Shift_JIS),
    and many others. Chardet uses statistical models and heuristics to guess the most likely encoding.
  doc_url: https://chardet.readthedocs.io
  dev_url: https://github.com/chardet/chardet

extra:
  recipe-maintainers:
    - dan-blanchard
    - jschueller
    - sigmavirus24
    - nehaljwani
