travis:
  secure:
    BINSTAR_TOKEN: lo/y1Mwx36CJq8KSRDkYfR5xXHhsGiwYU6Msuqa5FhBPZ2ScPUt2HZQwBrZAOJCRDz8s7PoxdppRc6qzXzYfktZSJPLcT1k2ygxdLFDpAoLSL37M6+vbupTduCexWaeiO88ysh5tkvGj8MfFu3CHg1CKWTw5Zp2ob5CudzTbTdlqnC/KZr6whnL84x9n5kB/2fAhZ7HEIF3rST7VGJdhdeo7hRirpoohBl27MzsedNigejkr4t/hOBtY8nWfwvH5JU39yRrha31oq4u5YuNTAgUyzIvSVCSLmEq/AhkmMQaZ8zHITQGXsQzjmWEMgNlOImWxSbrE7qZdDX4UapEFEzZprElGDttpn5mz/xwpaH9dbHKxFV29D0lX+4TWXa2YliHvjlHAhJkEuUIk20jbkRUNf8b0mbwqbQFBsTBrwslND34+a9kVlFDpINpsUVCF0L3zKTVDYJKQezjuRWNrbJhHUOLD62vgzE+G5WdpaAeasi0UH5nkFsmS5AtmNOKhbepmipSGuP2aF1RakYUFuC3tOX96NKHWyhR9fu6h6Wmw+cryu3mCwFx2SjC76RlBiWW14J2iwWIaVTFKSrpfW35v9LqFQw0qATH544GH5KxknvE2oV7Blh/nh0sHRyMl+h9lqmY58IwNJSpCiSSioWSAuKUDY/q0c8MtVCOTpAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
