travis:
  secure:
    BINSTAR_TOKEN: Snvi6L6o4plzJFnhmt2H7TGfxYhM/J3Myt0Q/ZhrnS4yO8fmU3flLEWUBquxEXbtkzwr+JZTlWZg01AHKMpbBeZ36zj/NtQa2G3dDngDRMgTwBVJ8pzFKs97SHSZRTIbCUHzHj3bLXN8Opshh3pPhqAA6lAz7JA5gwyOWlIiW/PupwoZFrNOLUg/R3uxq3KK9M5jHA2Y3EpYd9T0v9G9KFYEO1+7ioSWc5qfMckA8UTpdo5pNv4SeEhNkGTf9W1/rII7N4gfhs1hR67V2BFcv/s8Bd7KaaEUqGWUfmiFJT5M6AvxNHUxHZxrpcTh6rfSNAtw02OmNujB6fRXElVMJ9rpdrKOP25K4xGNl4kMzs9BQS3KRnsn+klbP39gwS3zKNxwgnzsrHxDCe8nJWHm9Yh+A84lzvozYCH9qMlBjuw3+xBzsIPeisPRenGktf3IKPm+AUqvCCCTtEYse6vujPAIA8EgxSlXdjkfbPcxQlaeMVDvnBkHRZPtrJ4rdyg0JNQLpsvhTJBQx0eFL0GSVOFxHQRGMRTqY2/eU8NR19BlMmDPyKLWDJMzcYXp984MmUl+yCXw1QZyIM2wq+sO8ABEZPpFQjWT78RGWB2d3JuMJQ+D7Y1vEGHuZCwrR2oSf9/hVELt7xqraqgWJrikg1HCTqlWsVsDlniQ3rMEEB0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
